---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "IMAGE"
  namespace: "default"
  labels:
    app: "IMAGE"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "IMAGE"
  template:
    metadata:
      labels:
        app: "IMAGE"
    spec:
      containers:
      - name: "IMAGE"
        image: "gcr.io/PROJECT/IMAGE:TAG"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "5"
            memory: "3G"
          requests:
            cpu: "2"
            memory: "500M"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "IMAGE-hpa-2t0w"
  namespace: "default"
  labels:
    app: "IMAGE"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "IMAGE"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
